import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Register from '../components/auth/Register';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Register />
      </main>
    </div>
  );
}
