import Head from 'next/head';
import Main from '../../components/common/Main';
import Organization from '../../components/organization/Organization';

export default function Organizations() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Main>
        <Organization />
      </Main>
    </>
  );
}
